universe = vanilla
initial_dir = $(seq_dir)
transfer_input_files = $(fwd_read), $(rev_read), /home/tslaird/microbial_community_test/BacFilt_wrapper.sh, /home/tslaird/microbial_community_test/BacFilt.R, /home/tslaird/microbial_community_test/R_libs.tar.gz, /home/tslaird/microbial_community_test/my_R.tar.gz
executable = /home/tslaird/microbial_community_test/BacFilt_wrapper.sh
output = $BacFilt.out
error = $BacFilt.err
log = $BacFilt.log

#transfer_output_files = $(seq_dir)/
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = 8GB
request_disk = 4GB

requirements = OSGVO_OS_STRING == "RHEL 7" && Arch == "X86_64" && HAS_MODULES == True

queue seq_dir,fwd_read,rev_read from seq_dirs.txt
